#!/bin/bash

set -e

# set the current time
time=$(date +'%Y%m%d-%H%M%S')

# loop through all the tables and back them up
echo "list" | sudo hbase shell -n | sed -e '1,/seconds/ d' |
while IFS='' read -r line || [[ -n "$line" ]]; do
    [ -n "$line" ] && sudo hbase snapshot create -n "${time}_${line}" -t "${line}" && echo "Backup created: ${time}_${line}"
done
